### ISSUE TITLE
Error when evaluating SSR module "astro-icon"

### ISSUE THREAD

**Issue by jjjrmy** [natemoo-re/astro-icon#231]
### What version of `astro-icon` are you using?

v1.1.0

### Astro Info

```block
Astro                    v4.13.2
Node                     v18.18.0
System                   macOS (arm64)
Package Manager          npm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/react
                         astro-auth

** I had to take out `astro-icon` Integration or it won't even run the command
```

### Describe the Bug

7:28:38 PM [vite] Error when evaluating SSR module /Users/***/Sites/***/astro.config.mjs: failed to import "astro-icon"
|- file:///Users/***/Sites/***/node_modules/@iconify/tools/lib/svg/index.mjs:1
import cheerio from 'cheerio';
       ^^^^^^^
SyntaxError: The requested module 'cheerio' does not provide an export named 'default'
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)

[astro] Unable to load your Astro config

The requested module 'cheerio' does not provide an export named 'default'
  Stack trace:
    at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)

### What's the expected result?

It should work

### Link to Minimal Reproducible Example

n/a

**Comment by jjjrmy** [comment]
It has something to do with the latest release of Cheerio
https://github.com/cheeriojs/cheerio/releases/tag/v1.0.0
It was tagged 6 hours ago. This seems more like an issue with `@iconify/tools`

**Comment by manuraj17** [comment]
Facing this as well 👍🏽

**Comment by Bran-mf** [comment]
Not sure how safe it is, but this worked for me (I'm just learning astro at this moment): 
I added this to the package.json  and installed dependencies,
 "overrides": {
    "astro-icon": {
      "cheerio": "1.0.0-rc.12"
    }
  }

**Comment by manuraj17** [comment]
> Not sure how safe it is, but this worked for me (I'm just learning astro at this moment): I added this to the package.json and installed dependencies, "overrides": { "astro-icon": { "cheerio": "1.0.0-rc.12" } }

Came to comment this. 

Works as a temporary solution, will use this until they get fixed.

**Comment by smorgrav** [comment]
Another way to solve it temporarily is to use resolutions in package.json (I struggled to get the overrides thing to work in a monorepo):

`  "resolutions": {
    "cheerio": "1.0.0-rc.12"
  }
`

**Comment by Lich496** [comment]
This problem is already solved in @iconify/tools version 4.
Below overrides worked for me, and I think it is the better solution.
```json
  "overrides": {
    "astro-icon": {
      "@iconify/tools": "^4.0.0"
    }
  }
```

**Comment by gilbertoxdev** [comment]
It worked for me by installing the latest version, npm install @iconify/tools --save

**Comment by adnansmajlovic** [comment]
I still get an error without: 

`"resolutions": { "cheerio": "1.0.0-rc.12" }`

**Comment by EveSunMaple** [comment]
`@iconify/tools` A new revised version has been released

https://github.com/iconify/tools/commit/3d8d54b7dc36bf40526abaffcc12022c6d636eed

**Comment by ameneses67** [comment]
I'm having the same issue.

**Comment by rderimay** [comment]
> I still get an error without:
> 
> `"resolutions": { "cheerio": "1.0.0-rc.12" }`

Same here. It did not work by any other way...

**Comment by Stretsh** [comment]
@rderimay @adnansmajlovic If you added the @iconify/tools override, don't forget to run `npm install` again.

**Comment by rderimay** [comment]
> @rderimay @adnansmajlovic If you added the @iconify/tools override, don't forget to run `npm install` again.

yes sure. Did it. Event deleted the `node_modules` folder to be sure.

**Comment by VisualEhrmanntraut** [comment]
On pnpm I had to do this instead

```json
  "pnpm": {
    "overrides": {
      "@iconify/tools": "^4.0.5"
    }
  }
```

**Comment by rderimay** [comment]
> On pnpm I had to do this instead
> 
> ```json
>   "pnpm": {
>     "overrides": {
>       "@iconify/tools": "^4.0.5"
>     }
>   }
> ```

Thanks! 🙏🏻 This is why it did not work as I am using pnpm. (ping @Stretsh)

**Comment by iEscapedVim** [comment]
still not fixed, astro still uses version 3.0.7 and even if you change the version to 4.0.5 I still get the error with cheerio...

**Comment by VisualEhrmanntraut** [comment]
For me it worked fine after using that override in my package.json and then running `pnpm up --latest`.

**Comment by sreejithkalarikkal** [comment]
> > On pnpm I had to do this instead
> > ```json
> >   "pnpm": {
> >     "overrides": {
> >       "@iconify/tools": "^4.0.5"
> >     }
> >   }
> > ```
> 
> Thanks! 🙏🏻 This is why it did not work as I am using pnpm. (ping @Stretsh)

Thanks The issue is solved now

**Comment by yangjuzi** [comment]
"overrides": {
    "astro-icon": {
      "@iconify/tools": "^4.0.0"
    }
  }

Thanks The issue is solved now

**Comment by sukantg** [comment]
> This problem is already solved in @iconify/tools version 4. Below overrides worked for me, and I think it is the better solution.
> 
> ```json
>   "overrides": {
>     "astro-icon": {
>       "@iconify/tools": "^4.0.0"
>     }
>   }
> ```

This worked for me. Amazing thanks!

**Comment by snimavat** [comment]
Facing same error and `npm install @iconify/tools --save` dint work for me

**Comment by Chrissdroid** [comment]
Seem to be fixed in [astro-icon@1.1.1](https://github.com/natemoo-re/astro-icon/releases/tag/astro-icon%401.1.1) by https://github.com/natemoo-re/astro-icon/pull/230 bumping to @iconify/tools@^4.0.4

At least i don't have build issues anymore on my side

**Comment by stramel** [comment]
I believe this is resolved. Closing.
